name: terraform-destroy-pipeline

trigger: none  # Manual only!

pool:
  name: myAgentPool

variables:
  azureServiceConnectionId: 'myServiceConnection'
  tfWorkingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environments/test'
  azureRg: 'Azuredevops'
  containerName: 'tfstate'
  storageAccountName: 'tfstate184604487'
  blobname: 'test.terraform.tfstate'

stages:
- stage: Destroy
  jobs:
  - job: DestroyInfrastructure
    steps:
    - task: TerraformInstaller@1
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: '1.13.2'

    - task: TerraformTask@5
      displayName: 'Terraform Init'
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: $(tfWorkingDirectory)
        backendServiceArm: '$(azureServiceConnectionId)'
        backendAzureRmResourceGroupName: '$(azureRg)'
        backendAzureRmStorageAccountName: '$(storageAccountName)'
        backendAzureRmContainerName: '$(containerName)'
        backendAzureRmKey: '$(blobname)'
        backendAzureRmUseCliFlagsForAuthentication: true
        backendAzureRmUseEntraIdForAuthentication: false

    - task: TerraformTask@5
      displayName: 'Terraform Destroy'
      inputs:
        provider: 'azurerm'
        command: 'destroy'
        workingDirectory: $(tfWorkingDirectory)
        commandOptions: '-auto-approve'
        environmentServiceNameAzureRM: '$(azureServiceConnectionId)'
