name: assurance-quality-pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
- main

pool: myAgentPool

variables:
  python.version: '3.12.3'
  azureServiceConnectionId: 'myServiceConnection'
  # Project root folder. Point to the folder containing manage.py file.
  projectRoot: $(System.DefaultWorkingDirectory)
  tfWorkingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environments/test'
  azureRg: 'Azuredevops' 
  containerName: 'tfstate' 
  storageAccountName: "tfstate184604487"
  blobname: 'test.terraform.tfstate'
  # Environment name
  environmentName: 'test-vm'

env:
  ARM_ACCESS_KEY: $(ARM_ACCESS_KEY)

stages:
#--------------------------------------------#  
# BUILD STAGE
#--------------------------------------------#    
- stage: Build
  jobs:
  - job: BuildInfrastructure
    steps:
    #--------------------------------------------#  
      - script: |
          echo  '$(ARM_ACCESS_KEY)'
          sudo apt-get update
          sudo apt-get install -y unzip
        displayName: 'Install unzip'

      # Use Terraform to create the Infrastructure      
      # Install Terraform on the pipeline agent 
      - task: TerraformInstaller@1
        displayName: 'Terrafom installation'
        inputs:
          terraformVersion: '1.13.2'
      
      # Run Terraform Init on the pipeline agent 
      - task: TerraformTask@5
        displayName: 'Terrafom init'
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: $(tfWorkingDirectory)
          backendServiceArm: '$(azureServiceConnectionId)'
          backendAzureRmResourceGroupName: '$(azureRg)'
          backendAzureRmStorageAccountName: '$(storageAccountName)'
          backendAzureRmContainerName: '$(containerName)'
          backendAzureRmKey: '$(blobname)'
          backendAzureRmAccessKey: '$(ARM_ACCESS_KEY)'
        
  
      
      # Run Terraform Validate
      - task: TerraformTask@5
        displayName: Terraform validate
        inputs:
          provider: 'azurerm'
          command: 'validate'
          environmentServiceNameAzureRM: '$(azureServiceConnectionId)'

    # OPTIONAL - This step is needed only if your Terraform VM uses an SSH key pair for login and you want your pipeline agent to connect to it. 
    # Generate an SSH key pair in your local/AZ Cloud shell. Use the public key in the Terraform VM module. 
    # Install public key and private key file to the pipeline agent, using the task below. 
    
    #- task: InstallSSHKey@0
     # inputs:
       # knownHostsEntry: 'KNOWN_HOSTS_STRING' 
        #sshPublicKey: 'PUBLIC_KEY'            
        #sshKeySecureFile: 'id_rsa'   # Use secure file feature in the pipeline library UI to save the "id_rsa" file, as mentioned here: https://learn.microsoft.com/en-us/azure/devops/pipelines/library/secure-files?view=azure-devops#add-a-secure-file
    
    # - task: DownloadSecureFile@1
    #  name: udacity_public_key
    #  displayName: 
    #  inputs:
    #   secureFile: 

      - task: TerraformTask@5
        displayName: Run Terraform Plan
        inputs:
            provider: 'azurerm'
            command: 'plan'
            commandOptions: '-out tfplan'
            environmentServiceNameAzureRM: '$(azureServiceConnectionId)'
            # Run Terraform Apply

      - task: TerraformTask@5
        displayName: Run Terraform apply
        inputs:
          provider: 'azurerm'
          command: 'apply'
          commandOptions: 'tfplan'
          workingDirectory: '$(tfWorkingDirectory)'
          environmentServiceNameAzureRM: '$(azureServiceConnectionId)'


    # ToDo: Change the workingDirectory path, as applicable to you
    # Destroy the resources in Azure by running a separate pipeline. 
    # - task: TerraformTaskV@5
    #   displayName: Terraform destroy
    #   inputs:
    #     provider: 'azurerm'
    #     command: 'destroy'
    #     workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environments/test'
    #     environmentServiceNameAzureRM: '$(azureServiceConnectionId)'

